import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — PcCoach",
  description: "Terms and conditions for using PcCoach.",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gray-900 text-white py-12 px-4">
      <div className="max-w-2xl mx-auto">
        <div className="mb-10">
          <Link href="/" className="text-gray-400 hover:text-white text-sm">
            &larr; Home
          </Link>
          <h1 className="text-4xl font-bold mt-4">Terms of Service</h1>
          <p className="text-gray-400 mt-2">Last updated: March 2026</p>
        </div>

        <div className="space-y-10 text-gray-300 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using PcCoach (&ldquo;the Service&rdquo;), you agree to be bound by these
              Terms of Service. If you do not agree, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
            <p>
              PcCoach is an AI-powered PC component recommendation tool. We help users identify
              suitable hardware components based on their stated requirements and budget. The
              Service is provided free of charge and is supported by affiliate commissions earned
              when users purchase products via links we provide.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. No Warranties</h2>
            <p className="mb-3">
              The recommendations generated by PcCoach are provided &ldquo;as is&rdquo; for informational
              purposes only. We make no warranties, express or implied, regarding:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-400">
              <li>The accuracy, completeness, or fitness for purpose of any recommendation</li>
              <li>The availability or current pricing of any recommended component</li>
              <li>The compatibility of recommended components with hardware not listed in your build</li>
              <li>The uninterrupted or error-free operation of the Service</li>
            </ul>
            <p className="mt-4">
              You are responsible for verifying component compatibility and pricing before making
              any purchase.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. Affiliate Links</h2>
            <p>
              PcCoach earns affiliate commissions from purchases made through links on our site.
              These commissions do not affect the price you pay. Our recommendations are generated
              based on your requirements; affiliate relationships do not influence which products
              are recommended.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. Third-Party Retailers</h2>
            <p>
              When you click a &ldquo;Buy&rdquo; link, you are redirected to a third-party retailer&apos;s
              website. PcCoach is not responsible for the content, policies, or practices of any
              third-party site. All purchases are governed by the retailer&apos;s own terms and
              conditions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable law, PcCoach shall not be liable for
              any direct, indirect, incidental, or consequential damages arising from your use of
              the Service or any purchase made based on our recommendations.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Acceptable Use</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc list-inside space-y-2 text-gray-400">
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to disrupt, overload, or exploit the Service or its infrastructure</li>
              <li>Scrape, crawl, or harvest data from the Service in an automated manner without our prior written consent</li>
              <li>Misrepresent yourself or provide false information when using the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Intellectual Property</h2>
            <p>
              All content on PcCoach — including the design, text, and software — is the property
              of PcCoach and is protected by applicable intellectual property laws. You may not
              reproduce or redistribute any part of the Service without our written permission.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. Changes to the Service</h2>
            <p>
              We reserve the right to modify or discontinue the Service at any time, with or
              without notice. We shall not be liable to you or any third party for any such
              modification or discontinuation.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">10. Governing Law</h2>
            <p>
              These Terms are governed by the laws of the Republic of Cyprus. Any disputes arising
              from these Terms shall be subject to the exclusive jurisdiction of the courts of
              Cyprus.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">11. Changes to These Terms</h2>
            <p>
              We may update these Terms from time to time. The date at the top of this page
              reflects the latest revision. Continued use of the Service after changes are posted
              constitutes your acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">12. Contact</h2>
            <p>
              For questions about these Terms, please{" "}
              <Link href="/contact" className="text-blue-400 hover:text-blue-300 underline">
                contact us
              </Link>
              .
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
